<a href="https://colab.research.google.com/github/Harshan18-k/Harshan-codeboosters-2026/blob/main/data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
print("Libraries is Downloaded Successfully !!!")

Libraries is Downloaded Successfully !!!

In [ ]:
import pandas as pd

data = pd.read_csv("/student_performance.csv")
print("Data is Loaded Successfully !!!!!!!")
print(data)

Data is Loaded Successfully !!!!!!!
    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

In [ ]:
data.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
data.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
data.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             30 non-null     int64
 1   name                   30 non-null     object
 2   age                    30 non-null     int64
 3   gender                 30 non-null     object
 4   department             30 non-null     object
 5   semester               30 non-null     int64
 6   math_score             30 non-null     int64
 7   science_score          30 non-null     int64
 8   english_score          30 non-null     int64
 9   programming_score      30 non-null     int64
 10  attendance_percentage  30 non-null     int64
 11  city                   30 non-null     object
 12  admission_year         30 non-null     int64
dtypes: int64(9), object(4)
memory usage: 3.2+ KB

In [ ]:
print("shape of the dataset ",data.shape)

shape of the dataset  (30, 13)

In [ ]:
print("rows contained in shape of the dataset",data.shape[0])

rows contained in shape of the dataset 30

In [ ]:
print("columns contained in shape of the dataset",data.shape[1])

columns contained in shape of the dataset 13

In [ ]:
print(data.columns)

Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')

In [ ]:
print(data.columns.to_list)

<bound method IndexOpsMixin.tolist of Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')>

In [ ]:
print(data.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
print("Initial Missing Values in Each Column")
print(data.isnull().sum())

Initial Missing Values in Each Column
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print("==== Student Names ====")
print(data['name'])

==== Student Names ====
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
print("Printing the Unique values")
print(data['department'].unique())

Printing the Unique values
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print("Counting the value of department")
print(data['department'].value_counts())

Counting the value of department
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
print("Department of Electronic communication engineering !!! ")
elec_std = data[data['department'] == 'Electronics']
print(elec_std)
print("")
total_score = data['math_score'] + data['science_score'] + data['english_score'] + data['programming_score']
print("Average Score ",total_score.mean())

Department of Electronic communication engineering !!!
    student_id           name  age  gender   department  semester  math_score  \
2         1003    Rohit Verma   19    Male  Electronics         2          65
5         1006    Meera Joshi   20  Female  Electronics         2          58
10        1011    Vikram Iyer   20    Male  Electronics         2          80
15        1016   Ritu Agarwal   20  Female  Electronics         2          87
20        1021  Harish Pillai   20    Male  Electronics         2          64
25        1026     Rekha Nair   20  Female  Electronics         2          72

    science_score  english_score  programming_score  attendance_percentage  \
2              74             61                 55                     78
5              66             70                 52                     72
10             75             68                 72                     83
15             83             86                 69                     93
20             70             67                 58                     74
25             77             73                 63                     82

                  city  admission_year  total_score
2                Delhi            2023          255
5                 Pune            2023          246
10             Chennai            2023          295
15                Agra            2023          325
20  Thiruvananthapuram            2023          259
25               Kochi            2023          285

Average Score  295.6666666666667

In [ ]:
print("Number of Students in Electronic communication engineering ",len(elec_std))

Number of Students in Electronic communication engineering  6

In [ ]:
print("electronic communication engineering student report")
print(elec_std[['name','gender','semester','attendance_percentage','programming_score']])

electronic communication engineering student report
             name  gender  semester  attendance_percentage  programming_score
2     Rohit Verma    Male         2                     78                 55
5     Meera Joshi  Female         2                     72                 52
10    Vikram Iyer    Male         2                     83                 72
15   Ritu Agarwal  Female         2                     93                 69
20  Harish Pillai    Male         2                     74                 58
25     Rekha Nair  Female         2                     82                 63

In [ ]:
print("Students with attendance percentage greater than 90%")
print(data[data['attendance_percentage']>90][['name','department', 'attendance_percentage']])

Students with attendance percentage greater than 90%
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [ ]:
print("Top performing students")
print(data[data['programming_score']>90] [['name','department', 'programming_score']])

Top performing students
              name        department  programming_score
0     Aarav Sharma  Computer Science                 91
4       Arjun Nair  Computer Science                 95
7      Divya Singh  Computer Science                 93
9       Ananya Das  Computer Science                 97
17  Swati Kulkarni  Computer Science                 92
21     Tanvi Mehta  Computer Science                 96
29  Akanksha Yadav  Computer Science                 94

In [ ]:
data['total_score'] = data['math_score'] + data['science_score'] + data['english_score'] + data['programming_score']

In [ ]:
print("Top performing students ")
print(data.sort_values(by='total_score',ascending = False)[['name','department','total_score']].head())

Top performing students
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

In [ ]:
dept_avg = data.groupby('department')['total_score'].mean().round(2)
print("==== Average department score ====")
print(dept_avg )

==== Average department score ====
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [ ]:
dept_avg = data.groupby('department')['total_score'].mean().round(2)
print("==== Descending order Average department score ====")
avg = dept_avg.sort_values(ascending = False)
print(avg)

==== Descending order Average department score ====
department
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Civil               235.80
Name: total_score, dtype: float64

In [ ]:
dept_avg = data.groupby('department')['total_score'].mean().round(2)
print("==== Ascending Order Average department score ====")
avg_as = dept_avg.sort_values(ascending = True)
print(avg_as)

==== Ascending Order Average department score ====
department
Civil               235.80
Mechanical          267.33
Electronics         277.50
Computer Science    340.15
Name: total_score, dtype: float64