<a href="https://colab.research.google.com/github/Harshan18-k/Harshan-codeboosters-2026/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)

In [ ]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
print("==== Warnings Ignored ====")
print("Pandas Installed :",pd.__version__)
print("Numpy Installed :",np.__version__)
print("Requests Installed :",requests.__version__)
print("==== Packages Installed Successfully ====")

==== Warnings Ignored ====
Pandas Installed : 2.2.2
Numpy Installed : 2.0.2
Requests Installed : 2.32.4
==== Packages Installed Successfully ====

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Summer_Internship_2026/messy_sales_data.csv")
print("=== Data Loaded Successfully ===")

=== Data Loaded Successfully ===

In [ ]:
print("Data Loaded : ",data.shape[0]," Rows And ",data.shape[1]," Columns ")

Data Loaded :  30  Rows And  9  Columns

In [ ]:
data.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [ ]:
print("=== Data Quantity Analysis ===")
print("")
print("Number of Missing values")
print(data.isnull().sum())
print("="*40)
print("Number of Duplicate Values")
print(data.duplicated().sum())
print("="*40)
print("Data Types of the elements")
print(data.dtypes)

=== Data Quantity Analysis ===

Number of Missing values
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64
========================================
Number of Duplicate Values
0
========================================
Data Types of the elements
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

In [ ]:
print("=== Unique category name ===")
print(data['category'].unique())
print("")
print("=== Sample Customer name ===")
print(data['customer_name'].dropna().unique()[:8])
print("")
print("=== Order Date analysis ===")
print(data['order_date'].unique()[:6])

=== Unique category name ===
['Electronics' 'Accessories' nan]

=== Sample Customer name ===
['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' 'Ananya Das' 'Vikram Iyer']

=== Order Date analysis ===
['2024-01-05' '2024-01-07' '2024-01-08' '2024-01-10' '07-01-2024'
 '2024-01-12']

In [ ]:
print("Number of Missing values")
print(data['quantity'].isnull().sum())
print("-"*40)
print("Number of Duplicate Values")
print(data['quantity'].duplicated().sum())

Number of Missing values
3
----------------------------------------
Number of Duplicate Values
20

In [ ]:
#copying the dataset to avoid the lose of data using copy() function

df = data.copy()
df.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [ ]:
print(df)

    order_id  customer_name     product     category  quantity  unit_price  \
0       1001   Ramesh Kumar      Laptop  Electronics       2.0       45000
1       1002     Priya Nair         NaN  Electronics       1.0       15000
2       1003     AMIT VERMA    Keyboard  Accessories       3.0        1200
3       1004   Sunita Patel     Monitor  Electronics       NaN       22000
4       1005   Ramesh Kumar      Laptop  Electronics       2.0       45000
5       1006    kiran mehta       Mouse  Accessories      10.0         800
6       1007   Deepak Singh  Headphones  Electronics       2.0        3500
7       1008            NaN      Webcam  Accessories       1.0        2500
8       1009     Ananya Das      Laptop  Electronics       1.0       45000
9       1010    Vikram Iyer    Keyboard  Accessories       5.0        1200
10      1011    Pooja Gupta     Monitor  Electronics       2.0       22000
11      1012     SURESH RAO     USB Hub  Accessories       8.0         600
12      1013    Meera Joshi      Laptop  Electronics       NaN       45000
13      1014     Arjun Nair  Headphones  Electronics       3.0        3500
14      1015    Tanvi Mehta      Webcam  Accessories       2.0        2500
15      1016    Kiran Mehta       Mouse  Accessories      10.0         800
16      1017   Deepak Singh    Keyboard  Accessories       5.0        1200
17      1018    Rohit Verma     Monitor  Electronics       1.0       22000
18      1019    Sneha Reddy      Laptop  Electronics       1.0       45000
19      1020  Gaurav Shukla     USB Hub  Accessories      15.0         600
20      1021   Nisha Kapoor  Headphones  Electronics       2.0        3500
21      1022    Ajay Tiwari      Webcam  Accessories       3.0        2500
22      1023     ANANYA DAS      Laptop  Electronics       1.0       45000
23      1024  Preeti Saxena    Keyboard  Electronics       4.0        1200
24      1025      Amit Bose       Mouse  Accessories       6.0         800
25      1026            NaN  Headphones  Electronics       1.0        3500
26      1027     Rekha Nair     Monitor          NaN       2.0       22000
27      1028  Harish Pillai      Laptop  Electronics       3.0       45000
28      1029   Sanjay Dubey     USB Hub  Accessories      10.0         600
29      1030  Kavya Nambiar      Webcam  Accessories       NaN        2500

    order_date                city    sales_rep
0   2024-01-05              Mumbai  Anil Sharma
1   2024-01-07               Delhi   Sunita Rao
2   2024-01-08           Bangalore  Anil Sharma
3   2024-01-10             Chennai   Ravi Kumar
4   2024-01-05              Mumbai  Anil Sharma
5   07-01-2024                Pune   Sunita Rao
6   2024-01-12           Hyderabad   Ravi Kumar
7   2024-01-13              Mumbai  Anil Sharma
8   2024-01-15             Kolkata   Sunita Rao
9   2024-01-15             Chennai   Ravi Kumar
10  2024-01-18               Delhi  Anil Sharma
11  2024-01-20           Bangalore   Sunita Rao
12  2024-01-22                Pune   Ravi Kumar
13  21-01-2024               Kochi  Anil Sharma
14  2024-01-25               Surat   Sunita Rao
15  2024-01-07                Pune   Sunita Rao
16  2024-01-28           Hyderabad   Ravi Kumar
17  2024-01-30               Delhi  Anil Sharma
18  2024-02-01           Hyderabad   Ravi Kumar
19  2024-02-03             Lucknow   Sunita Rao
20  2024-02-05          Chandigarh  Anil Sharma
21  2024-02-07              Bhopal   Ravi Kumar
22  2024-01-15             Kolkata   Sunita Rao
23  2024-02-10              Kanpur  Anil Sharma
24  2024-02-12             Kolkata   Sunita Rao
25  2024-02-14              Mumbai   Ravi Kumar
26  2024-02-15               Kochi  Anil Sharma
27  2024-02-18  Thiruvananthapuram   Ravi Kumar
28  2024-02-20           Allahabad   Sunita Rao
29  2024-02-22            Thrissur  Anil Sharma

In [ ]:
print(df.columns)

Index(['order_id', 'customer_name', 'product', 'category', 'quantity',
       'unit_price', 'order_date', 'city', 'sales_rep'],
      dtype='object')

In [ ]:
print(data['quantity'].isnull().sum())
print("=== Finding the Total Missing Values in the copied Dataset ===")
print(df.isnull().sum().sum())

3
=== Finding the Total Missing Values in the copied Dataset ===
7

In [ ]:
df['customer_name'].fillna('Unknown Customer' ,inplace = True)
print(df['customer_name'])

0         Ramesh Kumar
1           Priya Nair
2           AMIT VERMA
3         Sunita Patel
4         Ramesh Kumar
5          kiran mehta
6         Deepak Singh
7     Unknown Customer
8           Ananya Das
9          Vikram Iyer
10         Pooja Gupta
11          SURESH RAO
12         Meera Joshi
13          Arjun Nair
14         Tanvi Mehta
15         Kiran Mehta
16        Deepak Singh
17         Rohit Verma
18         Sneha Reddy
19       Gaurav Shukla
20        Nisha Kapoor
21         Ajay Tiwari
22          ANANYA DAS
23       Preeti Saxena
24           Amit Bose
25    Unknown Customer
26          Rekha Nair
27       Harish Pillai
28        Sanjay Dubey
29       Kavya Nambiar
Name: customer_name, dtype: object

In [ ]:
df['customer_name'].fillna('Unknown Customer')

0         Ramesh Kumar
1           Priya Nair
2           AMIT VERMA
3         Sunita Patel
4         Ramesh Kumar
5          kiran mehta
6         Deepak Singh
7     Unknown Customer
8           Ananya Das
9          Vikram Iyer
10         Pooja Gupta
11          SURESH RAO
12         Meera Joshi
13          Arjun Nair
14         Tanvi Mehta
15         Kiran Mehta
16        Deepak Singh
17         Rohit Verma
18         Sneha Reddy
19       Gaurav Shukla
20        Nisha Kapoor
21         Ajay Tiwari
22          ANANYA DAS
23       Preeti Saxena
24           Amit Bose
25    Unknown Customer
26          Rekha Nair
27       Harish Pillai
28        Sanjay Dubey
29       Kavya Nambiar
Name: customer_name, dtype: object

In [ ]:
# Fill numeric columns with mean
df['quantity'].fillna(df['quantity'].mean(), inplace=True)
df['quantity'].fillna(df['quantity'].mean())

0      2.000000
1      1.000000
2      3.000000
3      3.925926
4      2.000000
5     10.000000
6      2.000000
7      1.000000
8      1.000000
9      5.000000
10     2.000000
11     8.000000
12     3.925926
13     3.000000
14     2.000000
15    10.000000
16     5.000000
17     1.000000
18     1.000000
19    15.000000
20     2.000000
21     3.000000
22     1.000000
23     4.000000
24     6.000000
25     1.000000
26     2.000000
27     3.000000
28    10.000000
29     3.925926
Name: quantity, dtype: float64

In [ ]:
# Fill categorical columns with mode
df['city'].fillna(df['city'].mode()[0], inplace=True)
df['city'].fillna(df['city'].mode()[0])

0                 Mumbai
1                  Delhi
2              Bangalore
3                Chennai
4                 Mumbai
5                   Pune
6              Hyderabad
7                 Mumbai
8                Kolkata
9                Chennai
10                 Delhi
11             Bangalore
12                  Pune
13                 Kochi
14                 Surat
15                  Pune
16             Hyderabad
17                 Delhi
18             Hyderabad
19               Lucknow
20            Chandigarh
21                Bhopal
22               Kolkata
23                Kanpur
24               Kolkata
25                Mumbai
26                 Kochi
27    Thiruvananthapuram
28             Allahabad
29              Thrissur
Name: city, dtype: object

In [ ]:
print("\nAfter Fixing Missing Values:")
print(df.isnull().sum())
print("\nTotal Missing Values:", df.isnull().sum().sum())

After Fixing Missing Values:
order_id         0
customer_name    0
product          1
category         1
quantity         0
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

Total Missing Values: 2

In [ ]:
print("=== Total Missing Values in Product ===")
print(df['product'].isnull().sum())
df['product'].fillna(df['product'].mode()[0],inplace = True)
df['product'].fillna(df['product'].mode()[0])

=== Total Missing Values in Product ===
0

0         Laptop
1         Laptop
2       Keyboard
3        Monitor
4         Laptop
5          Mouse
6     Headphones
7         Webcam
8         Laptop
9       Keyboard
10       Monitor
11       USB Hub
12        Laptop
13    Headphones
14        Webcam
15         Mouse
16      Keyboard
17       Monitor
18        Laptop
19       USB Hub
20    Headphones
21        Webcam
22        Laptop
23      Keyboard
24         Mouse
25    Headphones
26       Monitor
27        Laptop
28       USB Hub
29        Webcam
Name: product, dtype: object

In [ ]:
print("=== Total Missing Values in Product ===")
print(df['product'].isnull().sum())

=== Total Missing Values in Product ===
0

In [ ]:
print("Before Deduplication : ",len(df),"rows")
print("Duplicate Rows : ",df.duplicated().sum())
print(df[df.duplicated(keep = False)][['order_id', 'customer_name', 'product', 'category', 'quantity',
       'unit_price', 'order_date', 'city', 'sales_rep']])
df.drop_duplicates(inplace = True)
print("After Deduplication : ",len(df),"rows")
print("Removed Rows : ",len(data) - len(df))

Before Deduplication :  30 rows
Duplicate Rows :  0
Empty DataFrame
Columns: [order_id, customer_name, product, category, quantity, unit_price, order_date, city, sales_rep]
Index: []
After Deduplication :  30 rows
Removed Rows :  0

In [ ]:
print("=== Sample Dates Before parsing ===")
print(df['order_date'].head(8).tolist())

df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=False,
    errors='coerce'
)
nat_count = df['order_date'].isnull().sum()
print("Unparsable dates : ",nat_count)
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.strftime('%B')
print("=== sample dates after parsing ===")
print(df[['order_date','year','month','month_name']].head(8))

=== Sample Dates Before parsing ===
[Timestamp('2024-01-05 00:00:00'), Timestamp('2024-01-07 00:00:00'), Timestamp('2024-01-08 00:00:00'), Timestamp('2024-01-10 00:00:00'), Timestamp('2024-01-05 00:00:00'), NaT, Timestamp('2024-01-12 00:00:00'), Timestamp('2024-01-13 00:00:00')]
Unparsable dates :  2
=== sample dates after parsing ===
  order_date    year  month month_name
0 2024-01-05  2024.0    1.0    January
1 2024-01-07  2024.0    1.0    January
2 2024-01-08  2024.0    1.0    January
3 2024-01-10  2024.0    1.0    January
4 2024-01-05  2024.0    1.0    January
5        NaT     NaN    NaN        NaN
6 2024-01-12  2024.0    1.0    January
7 2024-01-13  2024.0    1.0    January

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=True, errors='coerce')
df['day'] = df['order_date'].dt.day
df['month'] = df['order_date'].dt.month
df['year'] = df['order_date'].dt.year
df['month_name'] = df['order_date'].dt.strftime('%B')

print("DataFrame with 'day', 'month', 'year', and 'month_name' columns:")
print(df[['order_date', 'day', 'month', 'year', 'month_name']].head())

DataFrame with 'day', 'month', 'year', and 'month_name' columns:
  order_date   day  month    year month_name
0 2024-01-05   5.0    1.0  2024.0    January
1 2024-01-07   7.0    1.0  2024.0    January
2 2024-01-08   8.0    1.0  2024.0    January
3 2024-01-10  10.0    1.0  2024.0    January
4 2024-01-05   5.0    1.0  2024.0    January